# Generated by Django 6.0.3 on 2026-04-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age_student_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraising',
            name='amount_raised',
        ),
        migrations.RemoveField(
            model_name='fundraising',
            name='date_created',
        ),
        migrations.AddField(
            model_name='student',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('senate_president', 'Senate President'), ('deputy_senate_president', 'Deputy Senate President'), ('secretary', 'Secretary'), ('financial_secretary', 'Financial Secretary'), ('treasurer', 'Treasurer'), ('organising_committee', 'Organising Committee'), ('social_director', 'Social Director'), ('pro', 'PRO'), ('pro2', 'PRO II'), ('welfare', 'Welfare')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='member_type',
            field=models.CharField(choices=[('member', 'Student Member'), ('executive', 'Association Student Executive')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
