# Generated by Django 6.0.3 on 2026-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_executive_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='executive_position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('senate_president', 'Senate President'), ('deputy_senate_president', 'Deputy Senate President'), ('social_director', 'Social Director'), ('welfare', 'Welfare'), ('organising_committee', 'Organising Committee'), ('general_secretary', 'General Secretary'), ('assistant_general_secretary', 'Assistant General Secretary'), ('pro', 'PRO'), ('pro_ii', 'PRO II'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('student_member', 'Student Member')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='member_type',
            field=models.CharField(choices=[('student', 'Student'), ('president', 'President'), ('senate_president', 'Senate President'), ('deputy_senate_president', 'Deputy Senate President'), ('social_director', 'Social Director'), ('welfare', 'Welfare'), ('organising_committee', 'Organising Committee'), ('general_secretary', 'General Secretary'), ('assistant_general_secretary', 'Assistant General Secretary'), ('pro', 'PRO'), ('pro_ii', 'PRO II'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('student_member', 'Student Member')], default='student_member', max_length=50),
        ),
    ]
