# Generated by Django 6.0.3 on 2026-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_executive_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='executive_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
