# Generated by Django 6.0.3 on 2026-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Awaiting Verification'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
