# Generated by Django 6.0.3 on 2026-05-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_event_options_event_created_at_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='executive_position',
        ),
        migrations.AlterField(
            model_name='student',
            name='member_type',
            field=models.CharField(choices=[('student', 'Regular Student'), ('student_member', 'Financial Student Member')], default='student_member', max_length=50),
        ),
        migrations.CreateModel(
            name='ExecutiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('president', 'President'), ('senate_president', 'Senate President'), ('deputy_senate_president', 'Deputy Senate President'), ('social_director', 'Social Director'), ('welfare', 'Welfare'), ('organising_committee', 'Organising Committee'), ('general_secretary', 'General Secretary'), ('assistant_general_secretary', 'Assistant General Secretary'), ('pro', 'PRO'), ('pro_ii', 'PRO II'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary')], max_length=50, unique=True)),
                ('tenure', models.CharField(default='2026/2027', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executive_role', to='students.student')),
            ],
        ),
    ]
