# Generated by Django 6.0.3 on 2026-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_executive_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='member_type',
            field=models.CharField(choices=[('student', 'Regular Student'), ('student_member', 'Financial Student Member')], default='student', max_length=50),
        ),
    ]
