# Generated by Django 6.0.3 on 2026-05-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_executiveposition_tenure_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveposition',
            name='title',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('senate_president', 'Senate President'), ('deputy_senate_president', 'Deputy Senate President'), ('general_secretary', 'General Secretary'), ('assistant_general_secretary', 'Assistant General Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('pro', 'PRO'), ('pro_ii', 'PRO II'), ('social_director', 'Social Director'), ('welfare', 'Welfare'), ('organising_committee', 'Organising Committee')], max_length=100, unique=True),
        ),
    ]
