# Generated by Django 6.0.3 on 2026-05-26 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(help_text='e.g., Shell, Chevron, State Government', max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(help_text='Specify GPA, Department, or Level requirements')),
                ('amount', models.CharField(help_text='e.g., ₦150,000 / Year or Fully Funded', max_length=100)),
                ('application_link', models.URLField(max_length=500)),
                ('deadline', models.DateField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
